events {
    worker_connections 1024;
}

http {
    # Docker's embedded DNS server is at 127.0.0.11
    resolver 127.0.0.11 valid=5s;

    server {
        listen 80;

        location / {
            # Use dynamic resolution so NGINX re-resolves the IP
            # addresses of 'rateguard' via Docker's DNS round-robin.
            set $backend_servers http://rateguard:5000;
            proxy_pass $backend_servers;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
